DROP TABLE IF EXISTS RECORDS;

CREATE TABLE RECORDS    (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
RECORD_TYPE INT NOT NULL,
DOMAIN TEXT NOT NULL,
VALUE CHAR(45) NOT NULL,
TTL INT DEFAULT 600 NOT NULL
);

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'test.com', 1, '1.1.1.1');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'test.com', 1, '1.1.1.2');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'test.com', 2, 'ns1.test.com.');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'test.com', 2, 'ns2.test.com.');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'testcname.com', 5, 'blog.senevan.com.');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'testipv6.com', 28, '2001:0db8:85a3:0000:0000:8a2e:0370:7334');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'google.com', 15, '10 ASPMX.L.GOOGLE.COM');

INSERT INTO RECORDS ( DOMAIN, RECORD_TYPE, VALUE)
VALUES ( 'google.com', 15, '20 ALT1.ASPMX.L.GOOGLE.COM');